
package test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapResponderPortType", targetNamespace = "http://www.SoapClient.com/xml/SoapResponder.wsdl")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SoapResponderPortType {


    /**
     * 
     * @param bstrParam1
     * @param bstrParam2
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Method1", action = "http://www.SoapClient.com/SoapObject")
    @WebResult(name = "bstrReturn", partName = "bstrReturn")
    public String method1(
        @WebParam(name = "bstrParam1", partName = "bstrParam1")
        String bstrParam1,
        @WebParam(name = "bstrParam2", partName = "bstrParam2")
        String bstrParam2);

}
