
package test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * 
 * A SOAP service that echoes input parameters in the response
 * 
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapResponder", targetNamespace = "http://www.SoapClient.com/xml/SoapResponder.wsdl", wsdlLocation = "file:/C:/Users/Ramazan/Desktop/webService.wsdl")
public class SoapResponder
    extends Service
{

    private final static URL SOAPRESPONDER_WSDL_LOCATION;
    private final static WebServiceException SOAPRESPONDER_EXCEPTION;
    private final static QName SOAPRESPONDER_QNAME = new QName("http://www.SoapClient.com/xml/SoapResponder.wsdl", "SoapResponder");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Ramazan/Desktop/webService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPRESPONDER_WSDL_LOCATION = url;
        SOAPRESPONDER_EXCEPTION = e;
    }

    public SoapResponder() {
        super(__getWsdlLocation(), SOAPRESPONDER_QNAME);
    }

    public SoapResponder(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPRESPONDER_QNAME, features);
    }

    public SoapResponder(URL wsdlLocation) {
        super(wsdlLocation, SOAPRESPONDER_QNAME);
    }

    public SoapResponder(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPRESPONDER_QNAME, features);
    }

    public SoapResponder(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapResponder(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapResponderPortType
     */
    @WebEndpoint(name = "SoapResponderPortType")
    public SoapResponderPortType getSoapResponderPortType() {
        return super.getPort(new QName("http://www.SoapClient.com/xml/SoapResponder.wsdl", "SoapResponderPortType"), SoapResponderPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapResponderPortType
     */
    @WebEndpoint(name = "SoapResponderPortType")
    public SoapResponderPortType getSoapResponderPortType(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.SoapClient.com/xml/SoapResponder.wsdl", "SoapResponderPortType"), SoapResponderPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPRESPONDER_EXCEPTION!= null) {
            throw SOAPRESPONDER_EXCEPTION;
        }
        return SOAPRESPONDER_WSDL_LOCATION;
    }

}
